version: '2'
services:
  rpg-server:
    command: npm run dev:watchall
    container_name: rpg-server
    restart: on-failure:2
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - 5000:5000
    volumes:
      - './:/usr/src/app:ro'
      - /usr/src/app/node_modules
  rpg-postgres:
    container_name: rpg-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pwd
    ports:
      - 5432:5432
  rpg-mysql:
    container_name: rpg-mysql
    image: mysql:8.0.15
    command: ["--default-authentication-plugin=mysql_native_password", "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"]
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=mmorpg